In [ ]:
import pandas as pd
data = pd.read_csv('spam2.csv')
data.head()

label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...

In [ ]:
! pip install transformers torch

In [ ]:
from transformers import BertTokenizer, BertModel
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertModel.from_pretrained('bert-base-uncased')

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [ ]:
def get_bert_embeddings(text):
  inputs = tokenizer(text, return_tensors='pt', padding=True, truncation=True)
  with torch.no_grad():
    outputs = model(**inputs)
  cls_embeddings = outputs.last_hidden_state[:, 0, :]
  return cls_embeddings

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import numpy as np
import torch

In [ ]:
texts = data['text'].tolist()
lables = data['label'].map({'ham':0,'spam':1}).tolist()

In [ ]:
embeddings =[]
for text in texts:
  embedding = get_bert_embeddings(text)
  embeddings.append(embedding.numpy()[0])

In [ ]:
embeddings

[array([-1.51306808e-01, -3.22922111e-01,  1.89847231e-01, -1.81466281e-01,
        -3.31168115e-01, -2.83335209e-01,  5.26929557e-01,  3.88584167e-01,
         2.21095771e-01, -3.49603176e-01, -3.12813342e-01, -4.54583824e-01,
        -3.34612876e-01,  4.84128714e-01,  4.26734716e-01,  5.49708724e-01,
        -1.41616136e-01,  2.81167060e-01,  6.86609298e-02, -2.25147098e-01,
        -2.86757618e-01, -3.80712599e-01,  6.80412278e-02,  2.50983447e-01,
         1.69556588e-01, -1.38723001e-01,  4.35150228e-02, -1.71025291e-01,
        -1.67013690e-01,  3.37361753e-01,  6.62316307e-02,  6.08697593e-01,
        -6.46715581e-01,  1.58982530e-01,  3.21425885e-01,  2.43911117e-01,
         5.74573159e-01,  7.31349140e-02,  8.54543298e-02,  2.85771877e-01,
        -2.76449203e-01,  4.24772143e-01,  3.69383335e-01, -1.61036789e-01,
        -9.44774877e-03, -5.42102695e-01, -3.49438620e+00, -9.44716483e-03,
        -5.75480640e-01, -6.95724607e-01,  7.90509060e-02, -2.12581009e-01,
         1.5

In [ ]:
X = np.array(embeddings)
y = np.array(lables)

In [ ]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [ ]:
clf = LogisticRegression()
clf.fit(X_train,y_train)

LogisticRegression()

In [ ]:
accuracy = clf.score(X_test,y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 1.0


In [ ]:
text = " free lottery weekly camp"
bert_embeddings = get_bert_embeddings(text)
prediction = clf.predict(bert_embeddings)
print(f"Prediction: {prediction}")

Prediction: [1]


In [ ]:
!pip install sentence_transformers

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 227.1/227.1 kB 4.9 MB/s eta 0:00:00


In [ ]:
from sentence_transformers import SentenceTransformer,util

In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.7k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


1_Pooling/config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
file_path = '/content/sample1.txt'

In [ ]:
with open(file_path, 'r') as file:
    text_data = file.readlines()

In [ ]:
text_data = [line.strip() for line in text_data if line.strip()]

In [ ]:
text_embeddings = model.encode(text_data, convert_to_tensor=True)
text_embeddings

tensor([[ 0.0313,  0.0872, -0.0401,  ..., -0.0481, -0.0136,  0.0200],
        [-0.0272, -0.0254,  0.0140,  ..., -0.0796, -0.0529,  0.0663],
        [-0.0266,  0.0090, -0.0431,  ...,  0.0077, -0.0208,  0.0494],
        [ 0.0162, -0.0527, -0.0382,  ...,  0.0841,  0.0590, -0.0085],
        [ 0.0093,  0.0587, -0.0607,  ..., -0.0347, -0.0466, -0.0454],
        [-0.0215,  0.0121, -0.1062,  ...,  0.0181, -0.0071, -0.0112]])

In [ ]:
question = " what is a decimal numbers?"

In [ ]:
question_embeddings = model.encode(question, convert_to_tensor=True)

In [ ]:
question_embeddings

tensor([-1.9090e-02,  2.0465e-02, -8.5910e-02, -4.9298e-02, -9.7137e-02,
         2.7647e-02,  3.5008e-02,  5.2935e-02,  5.6762e-02, -1.3939e-02,
        -2.8748e-02, -2.9477e-02,  2.2625e-02,  6.6668e-02, -3.6963e-02,
        -1.1671e-01, -6.3186e-02,  6.3411e-03,  2.3485e-02,  2.6265e-03,
         5.0675e-02,  4.1595e-02, -2.2694e-02,  1.6920e-02,  3.1607e-02,
        -2.7052e-02, -4.9699e-02, -3.6654e-02, -3.2182e-02,  2.2934e-02,
        -2.4417e-02,  6.0398e-02,  5.8050e-02,  4.0754e-02, -5.0055e-02,
        -7.9837e-03,  8.1423e-02,  7.7947e-03, -3.0568e-02,  7.2927e-02,
         3.2660e-02, -5.3917e-02,  8.2805e-02,  1.0057e-02, -2.7064e-02,
         3.3849e-02, -4.6730e-02,  4.5961e-02, -1.2994e-02,  2.8371e-02,
         3.8860e-02,  3.4932e-02, -8.1474e-02, -2.5963e-03,  1.1318e-02,
         2.1680e-02, -7.8467e-03,  3.2596e-02,  2.1290e-02,  2.7193e-02,
         2.2840e-02, -3.1597e-02, -2.5435e-02, -3.6887e-02,  3.0143e-02,
        -3.9056e-02, -7.5423e-02, -1.0889e-01,  3.6

In [ ]:
similarity_scores = util.pytorch_cos_sim(question_embeddings, text_embeddings)

In [ ]:
best_match_idx = similarity_scores.argmax()

In [ ]:
answer = text_data[best_match_idx]
print(answer)

The decimal numeral system is the standard system for denoting integer and non-integer numbers. It is the extension to non-integer numbers of the Hindu–Arabic numeral system. The way of denoting numbers in the decimal system is often referred to as decimal notation.


In [ ]:
def q_a(question):
  question_embeddings = model.encode(question, convert_to_tensor=True)
  similarity_scores = util.pytorch_cos_sim(question_embeddings, text_embeddings)
  best_match_idx = similarity_scores.argmax()
  answer = text_data[best_match_idx]
  return answer


In [ ]:
q_a('what is a grade system')

'Under the new system during Covid-19 in UK  university teachers and their heads of department, will be asked to grades and rank their students. It is felt that as teachers know their students best, this is the most fair and accurate way of evaluation of a students performance across the courses of their A-Levels.'

In [ ]:
!pip install gradio

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.4/50.4 kB 2.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.1/18.1 MB 38.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 318.7/318.7 kB 18.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.9/93.9 kB 6.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 77.9/77.9 kB 5.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 141.9/141.9 kB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.3/10.3 MB 45.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 3.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 4.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.4/71.4 kB 4.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 130.2/130.2 kB 8.2 MB/s eta 0:00:00
  Attempting uninstall: tomlkit
    Found existing in

In [ ]:
import gradio as gr

In [ ]:
gr.Interface(fn=q_a,inputs='text',outputs='text').launch()

Setting queue=True in a Colab notebook requires sharing enabled. Setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
Running on public URL: https://3b4e67366cd8c41f2d.gradio.live

This share link expires in 72 hours. For free permanent hosting and GPU upgrades, run `gradio deploy` from Terminal to deploy to Spaces (https://huggingface.co/spaces)


another example

In [ ]:
!pip install sentence_transformers

In [ ]:
from sentence_transformers import SentenceTransformer,util

In [ ]:
model = SentenceTransformer('all-MiniLM-L6-v2')

/usr/local/lib/python3.10/dist-packages/transformers/tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [ ]:
 file_path = '/content/text1.txt'

In [ ]:
with open(file_path,'r')as file:
  text_data = file.readlines()

In [ ]:
text_data = [line.strip() for line in text_data if line.strip() ]

In [ ]:
text_embeddings = model.encode(text_data,convert_to_tensor=True)
text_embeddings

tensor([[ 6.3775e-02, -2.0191e-02,  1.2674e-02,  9.4366e-02, -2.1244e-03,
         -9.4755e-03,  9.8610e-02, -8.0036e-02,  6.8965e-02, -3.4973e-02,
         -4.3591e-02, -9.5925e-02, -2.6711e-02,  3.5041e-03, -2.4758e-02,
          1.4011e-02, -7.6486e-02, -4.4163e-02,  2.4885e-02,  2.0682e-02,
         -3.8391e-02,  3.1776e-02, -3.1366e-02, -9.9492e-04, -6.4628e-02,
         -3.6892e-03,  2.5530e-02,  3.7840e-03,  3.9780e-03, -2.9934e-02,
         -3.3238e-02, -1.2058e-01, -7.4444e-02,  5.5907e-02, -1.4466e-01,
          1.4349e-02,  3.4693e-02,  1.4540e-01, -1.4986e-02, -5.5961e-02,
         -3.7512e-02,  7.0810e-02, -6.9256e-02, -7.3458e-03,  4.1509e-03,
          7.9107e-03, -1.2440e-01, -1.9648e-02,  1.8454e-02, -8.9711e-02,
         -4.9595e-02, -2.6909e-02, -1.9885e-02,  6.7827e-02,  2.9025e-02,
         -6.0615e-02,  6.2169e-02, -3.3607e-02,  2.1999e-02,  8.5303e-02,
          2.2739e-02,  6.3748e-02,  2.4517e-02, -6.3751e-03,  3.4981e-02,
         -6.1256e-02,  4.8627e-02,  5.

In [ ]:
question = "who is shiva?"

In [ ]:
question_embeddings = model.encode(question,convert_to_tensor=True)

In [ ]:
question_embeddings

tensor([-7.3063e-02,  9.5798e-02, -3.9189e-02,  1.4013e-03, -1.0636e-02,
        -2.9601e-02,  9.6750e-02, -3.4317e-02, -8.8787e-03,  5.7670e-03,
         6.4354e-03, -7.8524e-02,  1.5296e-02,  2.4438e-02,  9.5448e-03,
         1.0923e-02, -1.9955e-02,  1.1985e-02, -4.5215e-02, -8.1477e-02,
         4.2683e-02,  6.9713e-02,  2.7305e-02, -1.4905e-02,  2.0995e-02,
        -4.6445e-02, -4.3486e-02, -5.7346e-03, -9.1337e-03, -3.1916e-02,
         4.3199e-02,  2.2175e-02, -7.8786e-02, -4.4602e-02, -5.2229e-02,
         4.5608e-02, -2.0804e-02,  8.0779e-02,  5.6900e-02, -6.6376e-02,
         4.3278e-02, -3.6757e-02,  3.0655e-04, -3.6349e-02,  4.9182e-02,
        -9.3898e-02, -3.7107e-03, -2.3557e-02,  5.4025e-02,  2.3867e-02,
        -3.0501e-02,  2.0812e-03,  7.2836e-02, -7.0237e-02,  8.3576e-02,
         1.4317e-02, -1.6612e-02, -8.7437e-02,  1.0406e-01,  2.2789e-02,
         5.2585e-02,  4.2252e-02, -7.9372e-02, -2.0692e-04,  6.1049e-02,
        -5.4893e-02,  7.1219e-02, -1.1186e-01,  2.3

In [ ]:
similarity_scores = util.pytorch_cos_sim(question_embeddings,text_embeddings)

In [ ]:
best_match_idx = similarity_scores.argmax()

In [ ]:
answer = text_data[best_match_idx]
print(answer)

Shiva is known as the destroyer god because he removes all evil from the world. His wife is the goddess Parvati or Devi Durga. According to Hindu legend, he has a blue neck because he swallowed a poison in order to save the universe. He has three eyes, the third eye is on his forehead.


In [ ]:
def q_a(question):
  question_embeddings = model.encode(question,convert_to_tensor=True)
  similarity_scores = util.pytorch_cos_sim(question_embeddings,text_embeddings)
  best_match_idx = similarity_scores.argmax()
  answer = text_data[best_match_idx]
  return answer